### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by Gynjn** [Tangshitao/MVDiffusion_plusplus#2]
Firstly, thanks for sharing your great work.

In page 7, I guess the generation mask should be 0? not 1?

Also I understand that the conditional mask is value 1 for all, and the generation mask is value 0 for all. Then how did you use the mask provided by the datasets?

**Comment by Tangshitao** [comment]
We use the object mask in the vae training and also the neus training. The mask is different from the mask we use in the diffusion model. The mask used in diffusion model is mainly for differentiate the conditional branch and generation branch and it's either all 0 or 1.
